# Generated by Django 6.0 on 2026-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('bmi_score', models.IntegerField(default=0)),
                ('mental_score', models.IntegerField(default=0)),
                ('journal_score', models.IntegerField(default=0)),
                ('diet_score', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
