# Generated by Django 6.0 on 2026-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_healthscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthscore',
            name='consistency_score',
            field=models.IntegerField(default=0),
        ),
    ]
